spring.application.name=tasks
# SQA - Motor McCall
sqa.weights.testability=0.4
sqa.weights.correctness=0.4
sqa.weights.maintainability=0.2
sqa.jacoco.path=target/site/jacoco/jacoco.xml
sqa.spotbugs.path=target/spotbugsXml.xml
