# src/main/resources/application.properties

# --- CONFIGURACIÓN BASE ---
spring.application.name=ApiEmpresarial_PDCA
server.port=${PORT:8080}

# --- SWITCH DE PERFILES ---
# Aquí cambias entre 'dev' o 'prod'. 
# Si no le pasas un parámetro al arrancar, usará este por defecto.
spring.profiles.active=dev
spring.application.name=tasks

# --- JWT ---
jwt.secret=${JWT_SECRET:super_secret_key_minimum_256_bits_for_hs256_algorithm_00}
jwt.expiration-ms=${JWT_EXPIRATION_MS:7200000}

# SQA - Motor McCall
sqa.weights.testability=0.4
sqa.weights.correctness=0.4
sqa.weights.maintainability=0.2
sqa.jacoco.path=target/site/jacoco/jacoco.xml
sqa.spotbugs.path=target/spotbugsXml.xml
