# ==========================================
# 1. BASE DE DATOS (Conexión)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/tasksdb
spring.datasource.username=root
spring.datasource.password=changeme
# Forzar el driver explícitamente ayuda a veces cuando Docker Compose interfiere
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# 2. FLYWAY (Migraciones)
# ==========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:/resources/db/migration
# Crea la tabla flyway_schema_history automáticamente si no existe
spring.flyway.baseline-on-migrate=true
# Permite ejecutar scripts de versiones anteriores que se te hayan olvidado (útil en dev)
spring.flyway.out-of-order=true
# Mantener en false en dev te permite usar flyway:clean si necesitas reiniciar la BD
spring.flyway.clean-disabled=false

# ==========================================
# 3. JPA / HIBERNATE
# ==========================================
# CRÍTICO: Hibernate ya no crea ni modifica tablas. Solo verifica que 
# las entidades de Java coincidan con lo que Flyway construyó en Postgres.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Desactiva el Anti-Patrón OSIV. Esto elimina el WARN de tus logs y mejora el rendimiento.
spring.jpa.open-in-view=false
#cambiado a update para que hibernate actualice las tablas en la BD ya que flyway no esta funcionando correctoo.
spring.jpa.hibernate.ddl-auto=validate

# ==========================================
# 4. LOGGING PARA DEPURACIÓN
# ==========================================
logging.level.com.empresa.tasks=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Logs específicos para ver el ciclo de vida de Flyway
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG